import { computed, nextTick, onMounted, onUnmounted, reactive, ref, type Ref } from 'vue'
import { beginDesign, designStageReady, designSelected, designSelection, designTargets, selectedDesign, changeComponent, checkpoint, reorderComponent, undoDesign, type DesignTarget } from '../visualDesign'
import { snapped } from '@shared/visualDesign'

/** Canvas geometry, pointer selection, dragging and preview navigation. */
export function useDesignCanvas(options: { select: (target: DesignTarget) => void; locked: (target: DesignTarget) => boolean; parent: Ref<DesignTarget | undefined>; exitOpen: Ref<boolean>; themeOpen: Ref<boolean>; requestClose: () => void }) {
 const { select, locked, parent, exitOpen, themeOpen, requestClose } = options
 const snap=ref(true),browse=ref(false),zoom=ref('fit'),scale=ref(1),viewport=ref<HTMLElement>()
 const logical=reactive({width:window.innerWidth,height:window.innerHeight}),box=ref({x:0,y:0,width:0,height:0}),insertion=ref<{x:number;y:number;width:number;height:number}>(),guideX=ref<number>(),guideY=ref<number>()
 const free=computed(()=>selectedDesign.value.mode==='free')
let raf=0,observer:ResizeObserver|undefined
function measure(){const r=designSelected.value?.element.getBoundingClientRect();if(r)box.value={x:r.x,y:r.y,width:r.width,height:r.height};raf=requestAnimationFrame(measure)}
function resizeWindow(){logical.width=window.innerWidth;logical.height=window.innerHeight;fit()}
function fit(){const area=viewport.value?.querySelector<HTMLElement>('.preview-scroll');if(!area)return;const r=area.getBoundingClientRect();scale.value=zoom.value==='100'?1:Math.max(.05,Math.min(1,(r.width-40)/logical.width,(r.height-40)/logical.height))}
function isTools(e:Event){return !!(e.target as Element)?.closest?.('[data-design-tools]')}
function navigation(e:Event){return !!(e.target as Element)?.closest?.('.nav-item,.nav-sub-item,.cfg-tabs button,.seg-tabs button,.tabs button,.settings-categories button,.settings-scopes button,[data-design-nav]')}
let drag:null|{x:number;y:number;ox:number;oy:number;width:number;height:number;resize:boolean;left:number;top:number;changed:boolean;target:DesignTarget}=null,drop:DesignTarget|undefined,dropBefore=true
function hit(e:MouseEvent|PointerEvent,deep=false){let el=(e.target as Element).closest<HTMLElement>('[data-ui]');if(!deep){el=(e.target as Element).closest<HTMLElement>('button,label,.card,article,section,h1,h2,h3,h4,p')||el}return designTargets.value.find(t=>t.element===el&&!t.decoration)}
function down(e:PointerEvent,resize=false){if(e.button!==0||(!resize&&isTools(e)))return;if(browse.value){if(!navigation(e)){e.preventDefault();e.stopImmediatePropagation()}return}if(!resize){const t=hit(e);if(!t)return;select(t)}const target=designSelected.value;if(!target)return;e.preventDefault();e.stopImmediatePropagation();if(locked(target))return;const r=target.element.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,ox:selectedDesign.value.x||0,oy:selectedDesign.value.y||0,width:r.width/scale.value,height:r.height/scale.value,resize,left:r.left,top:r.top,changed:false,target}}
function move(e:PointerEvent){if(!drag)return;const dx=(e.clientX-drag.x)/scale.value,dy=(e.clientY-drag.y)/scale.value;if(!drag.changed&&Math.abs(dx)+Math.abs(dy)<4)return
 if(!drag.resize&&!free.value){const candidates=designTargets.value.filter(t=>t!==drag!.target&&t.element.parentElement===drag!.target.element.parentElement&&!t.decoration);drop=candidates.find(t=>{const r=t.element.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom});if(drop){const r=drop.element.getBoundingClientRect(),horizontal=getComputedStyle(drop.element.parentElement!).flexDirection==='row';dropBefore=horizontal?e.clientX<r.left+r.width/2:e.clientY<r.top+r.height/2;insertion.value=horizontal?{x:dropBefore?r.left:r.right,y:r.top,width:3,height:r.height}:{x:r.left,y:dropBefore?r.top:r.bottom,width:r.width,height:3}}else insertion.value=undefined;drag.changed=true;return}
 if(!drag.changed){checkpoint();drag.changed=true}
 const p=drag.target.element.parentElement!.getBoundingClientRect(),s=scale.value
 if(drag.resize){const w=snapped(drag.width+dx,[],snap.value&&!e.altKey),h=snapped(drag.height+dy,[],snap.value&&!e.altKey);changeComponent({width:Math.max(8,Math.min(p.width/s,w.value)),height:Math.max(8,h.value)},false)}
 else{const targets=designTargets.value.filter(t=>t.element.parentElement===drag!.target.element.parentElement&&t!==drag!.target).map(t=>t.element.getBoundingClientRect());const xs=[p.left,p.right-drag.width*s,...targets.map(r=>r.left)].map(x=>x/s),ys=[p.top,p.bottom-drag.height*s,...targets.map(r=>r.top)].map(y=>y/s);const x=snapped(drag.left/s+dx,xs,snap.value&&!e.altKey),y=snapped(drag.top/s+dy,ys,snap.value&&!e.altKey);guideX.value=x.guide===undefined?undefined:x.guide*s;guideY.value=y.guide===undefined?undefined:y.guide*s;changeComponent({x:drag.ox+(Math.max(p.left/s,Math.min((p.right-drag.width*s)/s,x.value))-drag.left/s),y:drag.oy+(Math.max(p.top/s,Math.min((p.bottom-drag.height*s)/s,y.value))-drag.top/s)},false)}
}
function up(){if(drag?.changed&&!drag.resize&&!free.value&&drop)reorderComponent(drop,dropBefore);drag=null;drop=undefined;insertion.value=undefined;guideX.value=undefined;guideY.value=undefined}
function click(e:MouseEvent){if(!isTools(e)&&!(browse.value&&navigation(e))){e.preventDefault();e.stopImmediatePropagation()}}
function deepSelect(e:MouseEvent){if(isTools(e)||browse.value)return;const t=hit(e,true);if(t){select(t);e.preventDefault();e.stopImmediatePropagation()}}
function keys(e:KeyboardEvent){if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(exitOpen.value){exitOpen.value=false;return}if(themeOpen.value){themeOpen.value=false;return}if(designSelected.value&&parent.value){select(parent.value);return}requestClose();return}if(isTools(e))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undoDesign(e.shiftKey)}if(free.value&&designSelected.value&&!locked(designSelected.value)&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const n=e.shiftKey?10:1;changeComponent({x:(selectedDesign.value.x||0)+(e.key==='ArrowLeft'?-n:e.key==='ArrowRight'?n:0),y:(selectedDesign.value.y||0)+(e.key==='ArrowUp'?-n:e.key==='ArrowDown'?n:0)})}}
onMounted(async()=>{await beginDesign();await nextTick();designStageReady.value=true;window.addEventListener('resize',resizeWindow);observer=new ResizeObserver(fit);if(viewport.value)observer.observe(viewport.value);fit();raf=requestAnimationFrame(measure);document.addEventListener('pointerdown',down,true);document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',up,true);document.addEventListener('click',click,true);document.addEventListener('dblclick',deepSelect,true);document.addEventListener('keydown',keys,true)})
onUnmounted(()=>{designStageReady.value=false;window.removeEventListener('resize',resizeWindow);observer?.disconnect();cancelAnimationFrame(raf);document.removeEventListener('pointerdown',down,true);document.removeEventListener('pointermove',move,true);document.removeEventListener('pointerup',up,true);document.removeEventListener('click',click,true);document.removeEventListener('dblclick',deepSelect,true);document.removeEventListener('keydown',keys,true)})

 return { snap, browse, zoom, scale, viewport, logical, box, insertion, guideX, guideY, fit, down }
}
