// Real isolated Minecraft installation/launch via production IPC. No private pack,
// player account or other process is controlled. Test-only Fabric driver presses
// the client's actual demo button and reads its real player/GPU texture/options.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),Zip=require('adm-zip')
module.exports=async h=>{
 const root=path.resolve('out','game118-'+crypto.randomUUID());fs.mkdirSync(root,{recursive:true})
 const games=path.join(root,'games'),trigger=path.join(root,'game');fs.mkdirSync(games)
 const proof={complete:false,version:h.version,root,classification:'Real official 26.3/Fabric native Windows game through production installation, skin apply and launch IPC; test-only client driver enters its actual demo world, observes loaded player GPU texture and captures in-game screenshots. No real user data.',events:[]},save=()=>fs.writeFileSync(path.join(root,'proof.json'),JSON.stringify(proof,null,2))
 proof.platform=process.platform;if(process.platform==='darwin')proof.classification=proof.classification.replace('native Windows game','native Mac ARM64 game')
 const invoke=(c,...a)=>h.evaluate(`window.kamucl.invoke(${JSON.stringify(c)},...${JSON.stringify(a)})`,120000)
 let gameId,started=false
 const drain=async()=>{const b=await h.evaluate('window.__game118Events.splice(0)');proof.events.push(...b);save();return b}
 const until=async(label,read,ok,max=180000)=>{const end=Date.now()+max;while(Date.now()<end){const v=await read();if(ok(v))return v;if(fs.existsSync(trigger+'.error'))throw Error(fs.readFileSync(trigger+'.error','utf8'));await h.wait(500)}throw Error('Actual game timeout: '+label)}
 try{
  await h.main(`for(const [c,v]of __qaOriginalAppearanceHandlers){testElectron.ipcMain.removeHandler(c);testElectron.ipcMain.handle(c,v)}`)
  // Reuse only public official dependency/asset caches, not user MODs or saves.
  const cache=path.resolve('out/pcl-real-119-lYKtOa/games');for(const d of ['assets','libraries'])if(fs.existsSync(path.join(cache,d)))fs.cpSync(path.join(cache,d),path.join(games,d),{recursive:true})
  await invoke('settings:set',{gameDir:games,activeFolder:games,folders:[{path:games,name:'Owned native 118 game',isDefault:true}],mirror:'official',javaAuto:true,memoryAuto:false,memoryMB:2048,closeAfterLaunch:false,autoUpdate:false,resourcePackSync:true})
  await h.evaluate("window.__game118Events=[];for(const n of ['progress','installDone','launchState','launchLog'])window.kamucl.on('event:'+n,value=>__game118Events.push({name:n,value,at:Date.now()}))")
  await invoke('versions:install','26.3',{loader:'fabric',loaderVersion:'0.19.5',instanceName:'Owned-offline118'})
  const done=await until('official install',async()=>{await drain();return proof.events.find(e=>e.name==='installDone')?.value},v=>!!v,600000);assert(done.ok,JSON.stringify(done));gameId=done.installedId||done.versionId;assert(gameId)
  const instance=path.join(games,'versions',gameId),metadataFile=path.join(instance,gameId+'.json'),metadata=JSON.parse(fs.readFileSync(metadataFile,'utf8'))
  metadata._gameDir=true;metadata.arguments??={};metadata.arguments.game??=[];metadata.arguments.game.push('--demo');metadata.arguments.jvm??=[];metadata.arguments.jvm.push('-Dkamucl.gameProof='+trigger);fs.writeFileSync(metadataFile,JSON.stringify(metadata))
  const classes=path.join(root,'classes');fs.mkdirSync(classes);const jdk=process.env.JAVA_HOME||'C:/Program Files/Java/jdk-25.0.2',loader=path.join(games,'libraries/net/fabricmc/fabric-loader/0.19.5/fabric-loader-0.19.5.jar')
  if(process.platform==='darwin')assert(process.env.JAVA_HOME,'Native Mac game QA requires the configured actual ARM64 JDK')
  execFileSync(path.join(jdk,process.platform==='win32'?'bin/javac.exe':'bin/javac'),['--release','17','-cp',loader,'-d',classes,'tests/fixtures/OfflineGameProbe.java'],{windowsHide:true})
  fs.writeFileSync(path.join(classes,'fabric.mod.json'),JSON.stringify({schemaVersion:1,id:'kamucl_game_proof',version:'1',environment:'client',entrypoints:{client:['kamucltest.OfflineGameProbe']}}));fs.mkdirSync(path.join(instance,'mods'),{recursive:true});execFileSync(path.join(jdk,process.platform==='win32'?'bin/jar.exe':'bin/jar'),['cf',path.join(instance,'mods/native-proof-only.jar'),'-C',classes,'.'],{windowsHide:true})
  const bytes=await require('sharp')({create:{width:64,height:64,channels:4,background:'#25b191'}}).png().toBuffer(),skin=path.join(root,'synthetic.png');fs.writeFileSync(skin,bytes);proof.skinSha256=crypto.createHash('sha256').update(bytes).digest('hex')
  const account=await invoke('accounts:addOffline','OfflineNative118');await invoke('skin:offlineApply',skin,'slim',account.id);proof.account={type:account.type,username:account.username,uuid:account.uuid}
  const pack=new Zip(),packFile=path.join(root,'Native-pack118.zip');pack.addFile('pack.mcmeta',Buffer.from(JSON.stringify({pack:{min_format:[97,1],max_format:[97,1],description:'Original empty resource-pack acceptance fixture'}})));pack.writeZip(packFile);const imported=await invoke('defaultPacks:import',[packFile]);assert.equal(imported.length,1);proof.defaultPack={id:imported[0].id}
  const options=path.join(instance,'options.txt');fs.writeFileSync(options,'lang:en_us\nrenderDistance:4\nsimulationDistance:5\nmaxFps:60\n')
  await invoke('game:launch',gameId,null,games);started=true
  await until('real title atlas',async()=>{await drain();const bad=proof.events.find(e=>e.name==='launchState'&&e.value.status==='error');if(bad)throw Error(JSON.stringify(bad));return proof.events.some(e=>e.name==='launchLog'&&/Created: .*textures\/atlas\/gui/.test(e.value))},Boolean,300000)
  await h.wait(8000);fs.writeFileSync(trigger+'.command','start')
  await until('actual demo player',async()=>{await drain();return proof.events.some(e=>e.name==='launchLog'&&/joined the game|logged in with entity/.test(e.value))},Boolean,180000)
  await h.wait(12000);fs.writeFileSync(trigger+'.command','front');await h.wait(1500);fs.writeFileSync(trigger+'.command','capture')
  await until('actual player capture',()=>fs.existsSync(trigger+'.receipt'),Boolean);proof.player=fs.readFileSync(trigger+'.receipt','utf8');const textureHash=/body=minecraft\\:skins\/([a-f0-9]{40})/.exec(proof.player)?.[1];assert(textureHash,'Actual player must have a downloaded skin, not a built-in fallback');const textureFile=path.join(games,'assets/skins',textureHash.slice(0,2),textureHash);proof.loadedTexture={id:textureHash,sha256:crypto.createHash('sha256').update(fs.readFileSync(textureFile)).digest('hex')};assert.equal(proof.loadedTexture.sha256,proof.skinSha256,'PNG referenced by the actual GPU texture must match applied pixels');assert(proof.player.includes('gpuTexture=true'));assert(/model=slim/i.test(proof.player));assert(proof.player.includes(proof.defaultPack.id),'Actual game options must load the initial default pack')
  const shots=path.join(instance,'screenshots');await until('game screenshot',()=>fs.existsSync(shots)&&fs.readdirSync(shots).some(n=>n.endsWith('.png')),Boolean);for(const name of fs.readdirSync(shots).filter(n=>n.endsWith('.png'))){fs.copyFileSync(path.join(shots,name),path.join(root,'game-'+name));proof.screenshot='game-'+name}
  fs.writeFileSync(trigger+'.command','disable');await until('actual game saved disabled pack',()=>fs.readFileSync(options,'utf8').includes('resourcePacks:["vanilla"]'),Boolean);fs.writeFileSync(trigger+'.command','stop');await until('normal game close',async()=>{await drain();return proof.events.some(e=>e.name==='launchState'&&e.value.status==='exited')},Boolean,90000);started=false
  proof.optionsAfter=fs.readFileSync(options,'utf8').match(/^resourcePacks:.*$/m)?.[0];assert.equal(proof.optionsAfter,'resourcePacks:["vanilla"]');proof.worldSaved=fs.existsSync(path.join(instance,'saves','Demo_World','level.dat'));assert(proof.worldSaved)
  const previousExits=proof.events.filter(e=>e.name==='launchState'&&e.value.status==='exited').length;await invoke('game:launch',gameId,null,games);started=true;await until('second native launch',async()=>{await drain();return proof.events.filter(e=>e.name==='launchLog'&&/Created: .*textures\/atlas\/gui/.test(e.value)).length>=2},Boolean,300000);proof.optionsSecondLaunch=fs.readFileSync(options,'utf8').match(/^resourcePacks:.*$/m)?.[0];assert.equal(proof.optionsSecondLaunch,'resourcePacks:["vanilla"]','Launcher must preserve actual game choice on next launch');fs.writeFileSync(trigger+'.command','stop');await until('second normal game close',async()=>{await drain();return proof.events.filter(e=>e.name==='launchState'&&e.value.status==='exited').length>previousExits},Boolean,90000);started=false
  proof.complete=true;save();console.log(JSON.stringify({complete:true,root,player:proof.player,screenshot:proof.screenshot,worldSaved:true,secondLaunchSelectionPreserved:true}))
 }catch(e){proof.error=e.message;save();throw e}finally{if(started)try{fs.writeFileSync(trigger+'.command','stop');await until('owned failure cleanup',async()=>{await drain();return proof.events.some(e=>e.name==='launchState'&&e.value.status==='exited')},Boolean,90000)}catch(e){proof.cleanupError=e.message;save()}}
}
